name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages # Use the 'github-pages' environment
      url: ${{ steps.deployment.outputs.page_url }} # Set the environment URL to the deployed page

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci # Use ci instead of install for clean installation in CI environments

      # TODO run tests, skip for now

      - name: Build Project
        run: npm run build # this creates the dist folder

      - name: Upload production artifact and deploy to Pages
        id: deployment # Needed to capture the output URL
        uses: actions/deploy-pages@v4
        with:
          artifact_path: ./dist # Specify the path to your built application (the 'dist' folder)