name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages # Use the 'github-pages' environment
      url: ${{ steps.deployment.outputs.page_url }} # Set the environment URL to the deployed page

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci # Use ci instead of install for clean installation in CI environments

      # TODO run tests, skip for now

      - name: Build Project
        # Set the VITE_APP_BASE environment variable for the build command
        # Replace 'react-dataviz-demo' with your actual repository name
        run: VITE_APP_BASE=/react-dataviz-demo/ npm run build

      - name: Upload production artifact
        uses: actions/upload-pages-artifact@v3 # THIS IS THE CRUCIAL ACTION FOR PAGES ARTIFACTS
        with:
          path: ./dist # Path to your built application (the 'dist' folder)
          # The artifact name defaults to 'github-pages', which is required by deploy-pages@v4

  deploy:
    needs: build # This job depends on the 'build' job completing successfully
    runs-on: ubuntu-latest
    environment:
      name: github-pages # Use the 'github-pages' environment
      url: ${{ steps.deployment.outputs.page_url }} # Set the environment URL to the deployed page

    steps:
      - name: Deploy to GitHub Pages
        id: deployment # Needed to capture the output URL
        uses: actions/deploy-pages@v4 # This action now consumes the 'github-pages' artifact
